name: "BoundaryInvertedDoublePendulumSwingUp-v0"

eval_freq: 1000
batch_size: 256

medium_timesteps: 500000
expert_timesteps: 100000
random_samples: 200000
medium_samples: 200000
expert_samples: 200000